require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe OfferReductionsController, type: :controller do

  before { skip 'Code me maybe' }

  # This should return the minimal set of attributes required to create a valid
  # OfferReduction. As you add validations to OfferReduction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OfferReductionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all offer_reductions as @offer_reductions" do
      offer_reduction = OfferReduction.create! valid_attributes
          get :index, params: {}, session: valid_session
          expect(assigns(:offer_reductions)).to eq([offer_reduction])
    end
  end

  describe "GET #show" do
    it "assigns the requested offer_reduction as @offer_reduction" do
      offer_reduction = OfferReduction.create! valid_attributes
          get :show, params: {id: offer_reduction.to_param}, session: valid_session
          expect(assigns(:offer_reduction)).to eq(offer_reduction)
    end
  end

  describe "GET #new" do
    it "assigns a new offer_reduction as @offer_reduction" do
          get :new, params: {}, session: valid_session
          expect(assigns(:offer_reduction)).to be_a_new(OfferReduction)
    end
  end

  describe "GET #edit" do
    it "assigns the requested offer_reduction as @offer_reduction" do
      offer_reduction = OfferReduction.create! valid_attributes
          get :edit, params: {id: offer_reduction.to_param}, session: valid_session
          expect(assigns(:offer_reduction)).to eq(offer_reduction)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new OfferReduction" do
        expect {
                  post :create, params: {offer_reduction: valid_attributes}, session: valid_session
                }.to change(OfferReduction, :count).by(1)
      end

      it "assigns a newly created offer_reduction as @offer_reduction" do
              post :create, params: {offer_reduction: valid_attributes}, session: valid_session
              expect(assigns(:offer_reduction)).to be_a(OfferReduction)
        expect(assigns(:offer_reduction)).to be_persisted
      end

      it "redirects to the created offer_reduction" do
              post :create, params: {offer_reduction: valid_attributes}, session: valid_session
              expect(response).to redirect_to(OfferReduction.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved offer_reduction as @offer_reduction" do
              post :create, params: {offer_reduction: invalid_attributes}, session: valid_session
              expect(assigns(:offer_reduction)).to be_a_new(OfferReduction)
      end

      it "re-renders the 'new' template" do
              post :create, params: {offer_reduction: invalid_attributes}, session: valid_session
              expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested offer_reduction" do
        offer_reduction = OfferReduction.create! valid_attributes
              put :update, params: {id: offer_reduction.to_param, offer_reduction: new_attributes}, session: valid_session
              offer_reduction.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested offer_reduction as @offer_reduction" do
        offer_reduction = OfferReduction.create! valid_attributes
              put :update, params: {id: offer_reduction.to_param, offer_reduction: valid_attributes}, session: valid_session
              expect(assigns(:offer_reduction)).to eq(offer_reduction)
      end

      it "redirects to the offer_reduction" do
        offer_reduction = OfferReduction.create! valid_attributes
              put :update, params: {id: offer_reduction.to_param, offer_reduction: valid_attributes}, session: valid_session
              expect(response).to redirect_to(offer_reduction)
      end
    end

    context "with invalid params" do
      it "assigns the offer_reduction as @offer_reduction" do
        offer_reduction = OfferReduction.create! valid_attributes
              put :update, params: {id: offer_reduction.to_param, offer_reduction: invalid_attributes}, session: valid_session
              expect(assigns(:offer_reduction)).to eq(offer_reduction)
      end

      it "re-renders the 'edit' template" do
        offer_reduction = OfferReduction.create! valid_attributes
              put :update, params: {id: offer_reduction.to_param, offer_reduction: invalid_attributes}, session: valid_session
              expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested offer_reduction" do
      offer_reduction = OfferReduction.create! valid_attributes
      expect {
              delete :destroy, params: {id: offer_reduction.to_param}, session: valid_session
            }.to change(OfferReduction, :count).by(-1)
    end

    it "redirects to the offer_reductions list" do
      offer_reduction = OfferReduction.create! valid_attributes
          delete :destroy, params: {id: offer_reduction.to_param}, session: valid_session
          expect(response).to redirect_to(offer_reductions_url)
    end
  end

end
